from django_comments.signals import comment_will_be_posted
from django.dispatch import receiver
from django.core.mail import send_mail

# https://cs.wiktionary.org/wiki/Kategorie:Vulg%C3%A1rn%C3%AD_v%C3%BDrazy/%C4%8De%C5%A1tina
badwords = [
    'akcizák',
    'ambažúra',
    'babák',
    'bastard',
    'bembeřice',
    'blbka',
    'blejt',
    'bordel',
    'bordel jak v tanku',
    'bordelmamá',
    'brko',
    'buchta',
    'buk',
    'buzerace',
    'buzerant',
    'buzerantský',
    'buzerovat',
    'buzík',
    'buzna',
    'být putna',
    'chcanec',
    'chcaní',
    'chcanky',
    'chcát',
    'chcípnout',
    'chlívák',
    'chuj',
    'chujovina',
    'čokoláda',
    'čuba',
    'čubička',
    'čubka',
    'čurák',
    'čúrák',
    'čůrák',
    'cyp',
    'debil',
    'debilka',
    'debilní',
    'dělat si kozy',
    'dělat si prdel',
    'dement',
    'dementka',
    'díra',
    'do hajzlu',
    'do piče',
    'do piči',
    'do píči',
    'do prdele',
    'drbat',
    'drek',
    'dršťka',
    'drž hubu',
    'držka',
    'dylina',
    'frantík',
    'grázl',
    'hajzl',
    'hajzlbába',
    'hajzldědek',
    'hajzlpapír',
    'haur',
    'himlsakra',
    'hňup',
    'homokláda',
    'honit',
    'hořet koudel u prdele',
    'hovado',
    'hovno',
    'hovnocuc',
    'huba',
    'hulibrk',
    'idiot',
    'imbecil',
    'jako kdybys to vytáhl krávě z prdele',
    'jebačka',
    'jebat',
    'jejejnana',
    'kláda',
    'klandr',
    'kokot',
    'kokotina',
    'kouření',
    'kouřit',
    'kozomrd',
    'kretén',
    'kripl',
    'ksindl',
    'kulatina',
    'kunda',
    'kunďák',
    'kundička',
    'kundolap',
    'kuřbuřt',
    'kurevník',
    'kurevsky',
    'kurva',
    'kurvě',
    'kurvit',
    'kurvit se',
    'kurvítko',
    'líznout',
    'lulin',
    'lulín',
    'magor',
    'mamrd',
    'mindža',
    'mlít hovna',
    'mrd',
    'mrdačka',
    'mrdat',
    'mrdka',
    'mrdlota',
    'mrdna',
    'mrdník',
    'mrdnout',
    'mrdnutý',
    'na hovno',
    'na pyču',
    'nasraný',
    'nasrat',
    'negr',
    'obšoustník',
    'ocas',
    'ochlasta',
    'očurávat',
    'ojebat',
    'omrdat',
    'oprcat',
    'ošoustat',
    'ožrala',
    'pasák',
    'péro',
    'piča',
    'píča',
    'píchačka',
    'píchat',
    'pičovina',
    'píčovina',
    'pičus',
    'píčus',
    'pitoma',
    'pizda',
    'pochcat',
    'poser',
    'posera',
    'posraný',
    'posrat',
    'posrat se',
    'posrat se v kině',
    'prcat',
    'prd',
    'prdelatý',
    'prdelka',
    'prdět',
    'prdíček',
    'prdík',
    'přefiknout',
    'prkno',
    'průser',
    'pták',
    'řiťopich',
    'ser',
    'šoustat',
    'spermohlt',
    'šprcguma',
    'šprcka',
    'sráč',
    'sračka',
    'sraní',
    'srát',
    'srát se',
    'stát za hovno',
    'šuk',
    'šukání',
    'šulda',
    'šulin',
    'šulín',
    'v piči',
    'vandr',
    'vošoust',
    'vyjebat',
    'vysrat',
    'zajebaný',
    'zasraný',
    'zasrat',
    'zjebat',
    'zkurvený',
    'zkurvit',
    'zkurvysyn',
    'zmrd',
    'zmrdat',
    'zprcat',
]


@receiver(comment_will_be_posted, dispatch_uid="comment_will_be_posted_antivulgar")
def function(sender, comment, request, **kwargs):
    for bw in badwords:
        if bw in str(comment):
            send_mail(
                '[Volebni Kalkulacka] suspicious comment',
                f'{comment}',
                'comments@votesmart.com',
                ['admins@votesmart.com'],
                fail_silently=False,
            )

