FROM python:3
ENV PYTHONBUFFERED=1
WORKDIR /usr/src/app
COPY ./requirements/PREINSTALL.TXT .
COPY ./requirements/production.txt .
COPY ./requirements/base.txt
RUN pip install -r PREINSTALL.TXT
RUN pip install -r production.txt

