# Generated by Django 3.0.12 on 2021-02-27 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bod_Schuze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bod', models.IntegerField()),
                ('id_typ', models.IntegerField(null=True)),
                ('bod', models.IntegerField(null=True)),
                ('uplny_naz', models.CharField(max_length=2000, null=True)),
                ('uplny_kon', models.CharField(max_length=255, null=True)),
                ('poznamka', models.CharField(max_length=255, null=True)),
                ('pozvanka', models.IntegerField(null=True)),
                ('rj', models.IntegerField(null=True)),
                ('pozn2', models.CharField(max_length=255, null=True)),
                ('druh_bodu', models.IntegerField(null=True)),
                ('id_sd', models.IntegerField(null=True)),
                ('zkratka', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bod_Stav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bod_stav', models.IntegerField()),
                ('popis', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Druh_Tisku',
            fields=[
                ('id_druh', models.AutoField(primary_key=True, serialize=False)),
                ('druh_t', models.CharField(max_length=255)),
                ('nazev_druh', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hl_Hlasovani',
            fields=[
                ('id_hlasovani', models.AutoField(primary_key=True, serialize=False)),
                ('schuze', models.IntegerField(null=True)),
                ('cislo', models.IntegerField()),
                ('bod', models.IntegerField()),
                ('datum', models.CharField(max_length=255)),
                ('cas', models.CharField(max_length=255)),
                ('pro', models.IntegerField()),
                ('proti', models.IntegerField()),
                ('zdrzel', models.IntegerField()),
                ('nehlasoval', models.IntegerField()),
                ('prihlaseno', models.IntegerField()),
                ('kvorum', models.IntegerField()),
                ('druh_hlasovani', models.CharField(max_length=255)),
                ('vysledek', models.CharField(max_length=255)),
                ('nazev_dlouhy', models.CharField(max_length=255, null=True)),
                ('nazev_kratky', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organy',
            fields=[
                ('id_organ', models.AutoField(primary_key=True, serialize=False)),
                ('zkratka', models.CharField(max_length=1000)),
                ('nazev_organu_cz', models.CharField(max_length=2000)),
                ('nazev_organu_en', models.CharField(max_length=2000, null=True)),
                ('od_organ', models.CharField(max_length=255)),
                ('do_organ', models.CharField(max_length=255, null=True)),
                ('priorita', models.IntegerField(null=True)),
                ('cl_organ_base', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoby',
            fields=[
                ('id_osoba', models.AutoField(primary_key=True, serialize=False)),
                ('pred', models.CharField(max_length=255, null=True)),
                ('jmeno', models.CharField(max_length=255, null=True)),
                ('prijmeni', models.CharField(max_length=255, null=True)),
                ('za', models.CharField(max_length=255, null=True)),
                ('narozeni', models.CharField(max_length=255, null=True)),
                ('pohlavi', models.CharField(max_length=255, null=True)),
                ('zmena', models.CharField(max_length=255, null=True)),
                ('umrti', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prechody',
            fields=[
                ('id_prechod', models.AutoField(primary_key=True, serialize=False)),
                ('typ_prechodu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Typ_Akce',
            fields=[
                ('id_akce', models.AutoField(primary_key=True, serialize=False)),
                ('popis_akce', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Typ_Organu',
            fields=[
                ('id_typ_org', models.AutoField(primary_key=True, serialize=False)),
                ('typ_id_typ_org', models.IntegerField(null=True)),
                ('nazev_typ_org_cz', models.CharField(max_length=255, null=True)),
                ('nazev_typ_org_en', models.CharField(max_length=255, null=True)),
                ('typ_org_obecny', models.CharField(max_length=255, null=True)),
                ('priorita', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typ_Stavu',
            fields=[
                ('id_typ', models.AutoField(primary_key=True, serialize=False)),
                ('popis_stavu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Typ_Zakon',
            fields=[
                ('id_navrh', models.AutoField(primary_key=True, serialize=False)),
                ('druh_navrhovatele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zarazeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_funkce', models.IntegerField()),
                ('od_o', models.CharField(max_length=255)),
                ('do_o', models.CharField(max_length=255, null=True)),
                ('od_f', models.CharField(max_length=255, null=True)),
                ('do_f', models.CharField(max_length=255, null=True)),
                ('id_organ', models.ForeignKey(db_column='id_organ', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy')),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Osoby')),
            ],
        ),
        migrations.CreateModel(
            name='Typ_Funkce',
            fields=[
                ('id_typ_funkce', models.AutoField(primary_key=True, serialize=False)),
                ('typ_funkce_cz', models.CharField(max_length=255, null=True)),
                ('typ_funkce_en', models.CharField(max_length=255, null=True)),
                ('priorita', models.IntegerField(null=True)),
                ('typ_funkce_obecny', models.IntegerField(null=True)),
                ('id_typ_org', models.ForeignKey(db_column='id_typ_org', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Organu')),
            ],
        ),
        migrations.CreateModel(
            name='Tisky',
            fields=[
                ('id_tisk', models.AutoField(primary_key=True, serialize=False)),
                ('ct', models.IntegerField()),
                ('cislo_za', models.IntegerField()),
                ('navrhovatel', models.CharField(max_length=255)),
                ('nazev_tisku', models.CharField(max_length=255)),
                ('predlozeno', models.CharField(max_length=255)),
                ('rozeslano', models.CharField(max_length=255, null=True)),
                ('dal', models.CharField(max_length=255, null=True)),
                ('tech_nos_dat', models.CharField(max_length=255, null=True)),
                ('uplny_nazev_tisku', models.CharField(max_length=5000)),
                ('zm_lhuty', models.IntegerField()),
                ('lhuta', models.IntegerField()),
                ('rj', models.IntegerField()),
                ('t_url', models.CharField(max_length=255)),
                ('is_eu', models.IntegerField()),
                ('roz', models.CharField(max_length=255, null=True)),
                ('is_sdv', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('id_druh', models.ForeignKey(db_column='id_druh', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Druh_Tisku')),
                ('id_navrh', models.ForeignKey(db_column='id_navrh', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Zakon')),
                ('id_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Organy')),
                ('id_org_obd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Organy')),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Osoby')),
                ('id_stav', models.ForeignKey(db_column='id_stav', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Stavu')),
            ],
        ),
        migrations.CreateModel(
            name='Stavy',
            fields=[
                ('id_stav', models.AutoField(primary_key=True, serialize=False)),
                ('popis', models.CharField(max_length=255)),
                ('lhuta', models.IntegerField()),
                ('id_druh', models.ForeignKey(db_column='id_druh', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Druh_Tisku')),
                ('id_typ', models.ForeignKey(db_column='id_typ', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Stavu')),
                ('lhuta_where', models.ForeignKey(db_column='id_prechod', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Prechody')),
            ],
        ),
        migrations.CreateModel(
            name='Schuze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_schuze', models.IntegerField()),
                ('schuze', models.IntegerField()),
                ('od_schuze', models.CharField(max_length=255)),
                ('do_schuze', models.CharField(max_length=255, null=True)),
                ('aktualizace', models.CharField(max_length=255, null=True)),
                ('pozvanka', models.IntegerField(null=True)),
                ('id_org', models.ForeignKey(db_column='id_org', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy')),
            ],
        ),
        migrations.AddField(
            model_name='prechody',
            name='id_akce',
            field=models.ForeignKey(db_column='id_akce', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Akce'),
        ),
        migrations.AddField(
            model_name='prechody',
            name='kam',
            field=models.ForeignKey(db_column='kam', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Stavy'),
        ),
        migrations.AddField(
            model_name='prechody',
            name='odkud',
            field=models.ForeignKey(db_column='odkud', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Stavy'),
        ),
        migrations.CreateModel(
            name='Poslanec',
            fields=[
                ('id_poslanec', models.AutoField(primary_key=True, serialize=False)),
                ('web', models.CharField(max_length=255, null=True)),
                ('ulice', models.CharField(max_length=255, null=True)),
                ('obec', models.CharField(max_length=255, null=True)),
                ('psc', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('telefon', models.CharField(max_length=255, null=True)),
                ('fax', models.CharField(max_length=255, null=True)),
                ('psp_telefon', models.CharField(max_length=255, null=True)),
                ('facebook', models.CharField(max_length=255, null=True)),
                ('foto', models.IntegerField(null=True)),
                ('id_kandidatka', models.ForeignKey(db_column='id_kandidatka', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Organy')),
                ('id_kraj', models.ForeignKey(db_column='id_kraj', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy')),
                ('id_obdobi', models.ForeignKey(db_column='id_obdobi', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Organy')),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Osoby')),
            ],
        ),
        migrations.CreateModel(
            name='Pkgps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=555, null=True)),
                ('sirka', models.CharField(max_length=255, null=True)),
                ('delka', models.CharField(max_length=255, null=True)),
                ('id_poslanec', models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Poslanec')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField()),
                ('obvod', models.IntegerField()),
                ('strana', models.CharField(max_length=555)),
                ('id_external', models.IntegerField()),
                ('id_org', models.ForeignKey(db_column='id_org', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy')),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Osoby')),
            ],
        ),
        migrations.AddField(
            model_name='organy',
            name='id_typ_organu',
            field=models.ForeignKey(db_column='id_typ_organu', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Organu'),
        ),
        migrations.AddField(
            model_name='organy',
            name='organ_id_organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy'),
        ),
        migrations.CreateModel(
            name='Omluvy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.CharField(max_length=255, null=True)),
                ('od', models.CharField(max_length=255, null=True)),
                ('do', models.CharField(max_length=255, null=True)),
                ('id_organ', models.ForeignKey(db_column='id_organ', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy')),
                ('id_poslanec', models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Poslanec')),
            ],
        ),
        migrations.CreateModel(
            name='Hl_Poslanec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vysledek', models.CharField(max_length=2)),
                ('id_hlasovani', models.ForeignKey(db_column='id_hlasovani', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Hl_Hlasovani')),
                ('id_poslanec', models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Poslanec')),
            ],
        ),
        migrations.AddField(
            model_name='hl_hlasovani',
            name='id_organ',
            field=models.ForeignKey(db_column='id_organ', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy'),
        ),
        migrations.CreateModel(
            name='Hist',
            fields=[
                ('id_hist', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.CharField(max_length=255)),
                ('usnes_ps', models.IntegerField(null=True)),
                ('ps_id_posl', models.IntegerField(null=True)),
                ('orgv_p_usn', models.IntegerField()),
                ('zaver_publik', models.CharField(max_length=255, null=True)),
                ('zaver_sb_castka', models.IntegerField(null=True)),
                ('zaver_sb_cislo', models.IntegerField(null=True)),
                ('poznamka', models.CharField(max_length=255, null=True)),
                ('id_bod', models.ForeignKey(db_column='id_bod', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Bod_Schuze')),
                ('id_hlas', models.ForeignKey(db_column='id_hlas', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Hl_Hlasovani')),
                ('id_prechod', models.ForeignKey(db_column='id_prechod', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Prechody')),
                ('id_schuze', models.ForeignKey(db_column='id_schuze', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Schuze')),
                ('id_tisk', models.ForeignKey(db_column='id_tisk', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Tisky')),
                ('orgv_id_posl', models.ForeignKey(db_column='orgv_id_posl', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Poslanec')),
            ],
        ),
        migrations.CreateModel(
            name='Funkce',
            fields=[
                ('id_funkce', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_funkce_cz', models.CharField(max_length=255)),
                ('priorita', models.IntegerField(null=True)),
                ('id_organ', models.ForeignKey(db_column='id_organ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Organy')),
                ('id_typ_funkce', models.ForeignKey(db_column='id_typ_funkce', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Funkce')),
            ],
        ),
        migrations.AddField(
            model_name='bod_schuze',
            name='id_bod_stav',
            field=models.ForeignKey(db_column='id_bod_stav', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Bod_Stav'),
        ),
        migrations.AddField(
            model_name='bod_schuze',
            name='id_schuze',
            field=models.ForeignKey(db_column='id_schuze', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Schuze'),
        ),
        migrations.AddField(
            model_name='bod_schuze',
            name='id_tisk',
            field=models.ForeignKey(db_column='id_tisk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Tisky'),
        ),
        migrations.AddConstraint(
            model_name='schuze',
            constraint=models.UniqueConstraint(fields=('id_schuze', 'pozvanka'), name='id'),
        ),
        migrations.AddConstraint(
            model_name='bod_schuze',
            constraint=models.UniqueConstraint(fields=('id_bod', 'pozvanka'), name='id_bod_real'),
        ),
    ]
