# Generated by Django 3.0.12 on 2021-02-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bod_schuze',
            name='id_bod_real',
        ),
    ]
