# Generated by Django 3.0.12 on 2021-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0003_auto_20210228_0010'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schuze',
            name='id',
        ),
        migrations.AlterField(
            model_name='bod_schuze',
            name='id_schuze',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='schuze',
            constraint=models.UniqueConstraint(fields=('id_schuze', 'pozvanka'), name='id_schuze_real'),
        ),
    ]
