# Generated by Django 3.0.12 on 2021-02-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0004_auto_20210228_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typ_akce',
            name='popis_akce',
            field=models.CharField(max_length=10000),
        ),
    ]
