# Generated by Django 3.0.12 on 2021-02-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0005_auto_20210228_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavy',
            name='lhuta_where',
            field=models.ForeignKey(db_column='lhuta_where', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Prechody'),
        ),
    ]
