# Generated by Django 3.0.12 on 2021-02-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0007_auto_20210228_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prechody',
            name='id_akce',
            field=models.IntegerField(),
        ),
    ]
