# Generated by Django 3.0.12 on 2021-02-27 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0008_auto_20210228_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prechody',
            name='id_akce',
            field=models.ForeignKey(db_column='id_akce', on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Akce'),
        ),
        migrations.AlterField(
            model_name='stavy',
            name='lhuta_where',
            field=models.IntegerField(null=True),
        ),
    ]
