# Generated by Django 3.0.12 on 2021-02-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0009_auto_20210228_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tisky',
            name='id_org',
            field=models.ForeignKey(db_column='id_org', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Organy'),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='id_org_obd',
            field=models.ForeignKey(db_column='id_org_obd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Organy'),
        ),
    ]
