# Generated by Django 3.0.12 on 2021-02-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0010_auto_20210228_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tisky',
            name='is_eu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='lhuta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='rj',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='t_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='uplny_nazev_tisku',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='zm_lhuty',
            field=models.IntegerField(null=True),
        ),
    ]
