# Generated by Django 3.0.12 on 2021-02-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0011_auto_20210228_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tisky',
            name='id_navrh',
            field=models.ForeignKey(db_column='id_navrh', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Typ_Zakon'),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='id_org_obd',
            field=models.ForeignKey(db_column='id_org_obd', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Organy'),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='id_osoba',
            field=models.ForeignKey(db_column='id_osoba', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Osoby'),
        ),
    ]
