# Generated by Django 3.0.12 on 2021-02-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0012_auto_20210228_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tisky',
            name='zm_lhuty',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
