# Generated by Django 3.0.12 on 2021-02-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0013_auto_20210228_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tisky',
            name='navrhovatel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='nazev_tisku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tisky',
            name='predlozeno',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
