# Generated by Django 3.0.12 on 2021-02-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0016_auto_20210228_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bod_schuze',
            name='id_tisk',
            field=models.IntegerField(null=True),
        ),
    ]
