# Generated by Django 3.0.12 on 2021-02-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0017_auto_20210228_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist',
            name='orgv_p_usn',
            field=models.IntegerField(null=True),
        ),
    ]
