# Generated by Django 3.0.12 on 2021-02-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0018_auto_20210228_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist',
            name='id_bod',
            field=models.ForeignKey(db_column='id_bod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Bod_Schuze'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='id_hlas',
            field=models.ForeignKey(db_column='id_hlas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Hl_Hlasovani'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='id_prechod',
            field=models.ForeignKey(db_column='id_prechod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Prechody'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='id_tisk',
            field=models.ForeignKey(db_column='id_tisk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='psp_data.Tisky'),
        ),
    ]
