# Generated by Django 3.0.12 on 2021-02-28 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0021_auto_20210228_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist',
            name='ps_id_posl',
            field=models.ForeignKey(db_column='ps_id_posl', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='psp_data.Poslanec'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='zaver_sb_castka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hist',
            name='zaver_sb_cislo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
