# Generated by Django 3.0.12 on 2021-02-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0023_auto_20210228_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hist',
            name='id_schuze',
        ),
        migrations.AddField(
            model_name='hist',
            name='schuze',
            field=models.IntegerField(null=True),
        ),
    ]
