# Generated by Django 3.0.12 on 2021-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0027_zmatecne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmatecne',
            name='id_hlasovani',
            field=models.IntegerField(),
        ),
    ]
