# Generated by Django 3.1.7 on 2021-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0037_auto_20210407_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funkce',
            name='id_funkce',
            field=models.AutoField(db_column='id_funkce', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='osoby',
            name='id_osoba',
            field=models.AutoField(db_column='id_osoba', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typ_organu',
            name='id_typ_org',
            field=models.AutoField(db_column='id_typ_org', primary_key=True, serialize=False),
        ),
    ]
