# Generated by Django 3.1.7 on 2021-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0038_auto_20210408_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typ_stavu',
            name='popis_stavu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
