# Generated by Django 3.1.7 on 2021-04-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psp_data', '0039_auto_20210408_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omluvy',
            old_name='do',
            new_name='doo',
        ),
    ]
