# Generated by Django 3.1.7 on 2021-04-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210319_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kalkulacka_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kalkulacka_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
