# Generated by Django 3.1.7 on 2021-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210402_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to=''),
        ),
    ]
