# Generated by Django 3.1.7 on 2021-04-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poslanec', '0002_auto_20210402_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='id_poslanec',
            new_name='id_osoba',
        ),
    ]
